### ISSUE TITLE
Changes to `org-vcard-custom-styles-dir` should be reflected in `org-vcard--styles-dirs`

### ISSUE THREAD

**Issue by flexibeast** [flexibeast/org-vcard#38]
Cf. [this comment](https://github.com/flexibeast/org-vcard/issues/37#issue-1104825560).

**Comment by flexibeast** [comment]
Fixed in https://github.com/flexibeast/org-vcard/commit/74fc34319ce26455f58c7ae476b482d323796276.

cc: @lovrolu

**Comment by lovrolu** [comment]
Looks good!
